{
 "title": "Tailscale Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname" },
   {
    "name": "ListHostname",
    "query": {
     "query": "label_values(tailscale_hosts,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic IN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(traffic_type)(rate(tailscale_rx_bytes{src=~\"$hostname\"}[10m]))\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic OUT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(traffic_type)(rate(tailscale_rx_bytes{dst=~\"$hostname\"}[10m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num of devices by OS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without(hostname, instance, is_external,job, client_version, update_available, user)(tailscale_hosts)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of clients with pending update",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( count(tailscale_hosts{update_available=\"true\"}) / count(tailscale_hosts) ) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of machines up to date",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n100 * count(tailscale_hosts{update_available=\"false\"}) / count(tailscale_hosts{})\n\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num of devices by client version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without(hostname, instance, is_external,job, os, update_available, user)(tailscale_hosts)\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}